
[tool.black]
line-length = 80
target-version = ['py37']
include = '\.pyi?'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.misc
    | _build
    | __pycache__
    | _skbuild
    | build
    | build-timemory
    | dist
    | external
    | scripts
    | spack
    | docker
    | docs
    | hatchet
    | .pytest_cache
  )/
  | cmake/Templates/console-script.py.in
)
'''
