# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  cmake:
    paths:
      cmake: /usr/bin/cmake
    buildable: False
  dyninst:
    variants: build_type=Release
  mpich:
    variants: pmi=pmi2
  papi:
    variants: +rapl+powercap+lmsensors~example
  caliper:
    variants: +callpath+dyninst+gotcha+libpfm~papi~mpi+sampler
  openmpi:
    variants: ~vt-pmi+cuda+thread_multiple fabrics=auto
  tau:
    variants: ~ompt+openmp+papi~pdt+pthreads+python+mpi~likwid+libunwind~cuda~phase
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag, fj, gfortran]
    providers:
      D: [ldc]
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw]
      gl: [mesa+opengl, opengl]
      glx: [mesa+glx, opengl]
      glu: [mesa-glu, openglu]
      golang: [gcc]
      iconv: [libiconv]
      ipp: [intel-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      lapack: [openblas]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [mpich]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack]
      sycl: [hipsycl]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      unwind: [libunwind]
      sycl: [hipsycl]
    permissions:
      read: world
      write: user
