name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  release:
    if: github.repository == 'NERSC/timemory'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Generate Release
        uses: softprops/action-gh-release@v1
        with:
          draft: False
          generate_release_notes: True
